### ISSUE TITLE
install script and instruction

### ISSUE THREAD

**Issue by stoeffel** [jwoudenberg/brangelina#4]
@SamGerber would be interested in using it.

**Comment by jwoudenberg** [comment]
:thumbsup: 

Instruction should be pretty easy, a script would be a bit harder because it contains a bunch of platform-dependant instructions to get dependencies:
- python2 + neovim plugin
- python3 + neovim plugin
- ruby neovim plugin
- fzf installation (check is this required or does it come with fzf.vim?)
