### ISSUE TITLE
gf doesn't work

### ISSUE THREAD

**Issue by stoeffel** [jwoudenberg/brangelina#5]

**Comment by jwoudenberg** [comment]
It doesn't work for me in rails files (this was fixed for me by installing tpope's rails plugin before).

It does work for my in Elm, but only if I start vim while in the root directory of the elm project. This was broken by installing tpope's rails plugin because it started using the ruby resolver for elm files.

Does it work the same for you? We could investigate:
- [ ] Fixing ruby file resolving in elm files when using the rails plugin.
- [ ] Fixing gf to work in Elm regardless of the cwd.
